version: '3.8'


services:
  mongodb:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongosir
      - MONGO_INITDB_ROOT_PASSWORD=mongopass

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  gateway:
    build: webgateway
    restart: always
    command: python manage.py migrate & python manage.py runserver
    ports:
      - 8000:8000

  faust:
    build: faust_app
    restart: always
    command: python manage.py worker
