version: '3.8'


services:
  mongodb:
    image: mongo:6.0.2
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongosir
      - MONGO_INITDB_ROOT_PASSWORD=mongopass

  gateway:
    build: webgateway
    restart: always
    command: python manage.py runserver
    ports:
      - 8000:8000

  faust:
    build: faust_app
    restart: always
    command: python manage.py worker
