version: '3.0'

services:
  # Zookeeper
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    network_mode: "host"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # Kafka

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:2
    restart: always
    network_mode: "host"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://127.0.0.1:9092,EXTERNAL://127.0.0.1:9093"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_NUM_NETWORK_THREADS: 4
      KAFKA_NUM_IO_THREADS: 4
      KAFKA_BACKGROUND_THREADS: 10
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3
    depends_on:
      - zookeeper

  # Kafka-UI
  kafka_ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    restart: always
    network_mode: "host"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 127.0.0.1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: 127.0.0.1:2181
      SERVER_PORT: 8081